### PR TITLE
Feature/maven release

### PR DESCRIPTION
**Pull request by tomtzook**
At the moment, this only allows for manual publishing.
We can modify later to allow continuous deployment with tarvis.

### CODE REVIEW

**Comment by dandeduck** [comment]
Why not do CD with GitHub actions? it's great. Check if there is already an action for maven (there probably is) we can also chain it with Travis tests if you want, or use GitHub for unit tests too.

**Comment by dandeduck** [comment]
> Why not do CD with GitHub actions? it's great. Check if there is already an action for maven (there probably is) we can also chain it with Travis tests if you want, or use GitHub for unit tests too.

Anyway, this doesn't add CD anyway, so you can merge is as far as I'm aware. Just something to consider adding later

**Review by dandeduck — APPROVED** [review]
gud

**Comment by tomtzook** [comment]
> Why not do CD with GitHub actions? it's great. Check if there is already an action for maven (there probably is) we can also chain it with Travis tests if you want, or use GitHub for unit tests too.

Your CI already uses travis, so CD should be there too.

**Pull request merged**
